# Generated by Django 3.2.4 on 2021-06-18 15:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Список тэгов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
