# Generated by Django 3.2.4 on 2021-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical ('Задача',)"},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': ('Задача',), 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
